language: java
sudo: false
script: mvn clean verify
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - petteraatomren@gmail.com
    on_failure: [always|never|change] # default: always
